---

resources:
- name: concourse-app
  type: git
  source:
    uri: https://github.com/wellfreire/concourse-tutorial

jobs:
- name: unit-test
  public: true
  serial: true
  plan:
  - get: concourse-app
    trigger: true

  - task: unit test
    config:
        platform: linux

        image_resource:
            type: docker-image
            source: {repository: golang, tag: "1"}

        run:
            path: sh
            args:
            - -exc
            - |
                cd concourse-app

        inputs:
        - name: concourse-app
