---

resource_types    :
- name          : pull-request
  type          : docker-image
  source        :
    repository  : jtarchie/pr

resources:
- name: concourse-app
  type: git
  source:
    uri: https://github.com/wellfreire/concourse-tutorial
- name          : app-pr
  type          : pull-request
  source        :
    uri         : https://github.com/wellfreire/concourse-tutorial
    repo        : wellfreire/concourse-tutorial

jobs:

- name: unit-test
  public: true
  serial: true
  plan:
  - get: concourse-app
    trigger: true

  - task: unit test
    config:
        platform: linux

        image_resource:
            type: docker-image
            source: {repository: golang, tag: "1"}

        run:
            path: sh
            args:
            - -exc
            - |
                cd concourse-app
                make deps
                make test

        inputs:
        - name: concourse-app

- name: app-pr
  plan:
  - get: app-pr
    trigger: true

  - put: app-pr
    params:
        path: app-pr
        context: php-tests
        status: pending